packages:
  - artifacts/*
  - lib/*

autoInstallPeers: false

catalog:
  '@tanstack/react-query': ^5.90.21
  '@types/node': ^25.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  react: 19.1.0
  react-dom: 19.1.0
  tsx: ^4.21.0
  zod: 3.25.76

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@replit/*'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver

overrides:
  '@clerk/clerk-js': 6.7.5
  '@clerk/react': 6.4.3
  '@clerk/shared': 4.8.3
  'brace-expansion@>=2.0.0 <3.0.0': 2.0.3
  'brace-expansion@>=5.0.0 <6.0.0': 5.0.6
  fast-uri: 3.1.2
  ip-address: 10.1.1
  js-cookie: 3.0.7
  lodash: 4.18.0
  path-to-regexp: 8.4.0
  'picomatch@>=2.0.0 <3.0.0': 2.3.2
  'picomatch@>=4.0.0 <5.0.0': 4.0.4
  postcss: 8.5.10
  qs: 6.15.2
  ws: 8.20.1
  yaml: 2.8.3
  '@esbuild-kit/esm-loader': npm:tsx@^4.21.0
  '@expo/ngrok-bin>@expo/ngrok-bin-darwin-arm64': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-darwin-x64': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-freebsd-ia32': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-freebsd-x64': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-linux-arm': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-linux-arm64': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-linux-ia32': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-sunos-x64': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-win32-ia32': '-'
  '@expo/ngrok-bin>@expo/ngrok-bin-win32-x64': '-'
